language: node_js

node_js:
  - 0.10

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-router-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - npm install
  - npm install -g gulp
  - npm install -g karma-cli

script:
  - gulp build
  - karma start --sauce
  - karma start karma.es5.conf.js --sauce

after_script:
